#!/bin/bash
#
#    create_debian - helper script to create the debian packages
#    Copyright:
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

param=$1
SIGN_BY="tsagatakis@protonmail.com"

top_dir="$(git rev-parse --show-toplevel)"
cd "$top_dir" || exit

# hack for travis
if [[ $param == "--travis" ]]; then
  # install dependencies
  sudo apt-get update
  sudo apt-get install -y devscripts equivs lintian
  sudo mk-build-deps --install "${top_dir}/debian/control"
fi

#
# Make Debian package
#
# shellcheck disable=SC2034
DEBUILD_DPKG_BUILDPACKAGE_OPTS="--build=full"
if [[ $param == "--sign" ]]; then
  debuild -k${SIGN_BY} --force-sign
else
  debuild
fi

## move source artifacts
VERSION=$(dpkg-parsechangelog -S Version)
ARTIFACTS="dist"
mkdir -p ${ARTIFACTS}
rm -f ${ARTIFACTS}/*
mv ../ucare*.deb ${ARTIFACTS}
mv "../ucaresystem_${VERSION}"*.* ${ARTIFACTS}
mk-build-deps "${top_dir}/debian/control"
mv "ucaresystem-build-deps_${VERSION}_all.deb" ${ARTIFACTS}

if [[ ! $param == "--travis" ]]; then
  read -t 10 -n 1 -rp "Install package? Yes/No " yn
  echo "Give me give me give me your root"
  case $yn in
    [Yy]* )
      sudo dpkg -i "dist/ucaresystem_${VERSION}_all.deb"
      ucaresystem --version
    ;;
  esac
fi
