#!/bin/bash
# uCareSystem Core Launcher
# Copyright (c) 2017 Salih Emin. All rights reserved.
# Use of this source code is governed by GPLv3 license that can be
# found in the LICENSE file.

terms=(x-terminal-emulator gnome-terminal konsole  i3-sensible-terminal uxterm xterm rxvt)
for t in ${terms[*]}
do
    if [ $(command -v $t) ]
    then
        detected_term=$t
        break
    fi
done


/usr/bin/pkexec  $(which ${detected_term}) -title 'uCareSystem Core'  -e ucaresystem --wait 
