#!/usr/bin/env bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2154,SC2034

## Ensure this file can only be sourced once
check_eol_loaded=${check_eol_loaded:-}
if [[ -n ${check_eol_loaded} ]]; then
  echo "Warning: This file can only be sourced once"
  return 1
fi
check_eol_loaded=true

function check_eol() {

  valid_ids=("Debian" "Ubuntu")
  if [[ ! "${valid_ids[*]}" == *"${DISTRIBUTION_ID}"* ]]; then
    header_text "Your distribution is '${DISTRIBUTION_ID}', DISTRIBUTION_CODENAME:'${DISTRIBUTION_CODENAME}'."
    return
  fi

  supported_distro=$(${DISTRO_INFO} --supported)
  days=$(${DISTRO_INFO} --series="${DISTRIBUTION_CODENAME}" --days)

  if [[ "${supported_distro[*]}" == *"${DISTRIBUTION_CODENAME}"* ]]; then
    header_text "Your distribution '${GREEN}${DISTRIBUTION_ID}${NORMAL}', DISTRIBUTION_CODENAME:'${GREEN}${DISTRIBUTION_CODENAME}${NORMAL}' is not at eol."
    if [ ! "${days}" == "(unknown)" ]; then
      if [[ "${days}" == *"-"* ]]; then
        header_text "The was a new distribution version before ${days//-/} days. Consider an upgrade."
      else
        header_text "Expect a new version of your distribution in ${days} days."
      fi
    fi
    return
  else
    header_text "Your distribution '${DISTRIBUTION_ID}', DISTRIBUTION_CODENAME:'${DISTRIBUTION_CODENAME}' is reach the end of support"
    echo "  The end of support was before ${days//-/} days."
    echo "  Please upgrade your distribution to a latest release!"
    echo "  Try run: $(basename "${0}") --upgrade"
  fi
}

#
# Standalone
#
if [[ "${FUNCNAME[0]}" != source ]]; then
  base_dir=$(dirname "$0")
  # shellcheck source=base
  source "${base_dir}"/config
  basic_setup

  # DISTRIBUTION_ID="Ubuntu" && DISTRIBUTION_CODENAME="focal"

  header_text "Get distribution info (standalone version)."

  EXEC=${EXEC:=yes_opp}
  EXEC=no_opp
  [[ $EXEC == "yes_opp" ]] && check_root_priv
  check_eol
fi