#!/usr/bin/env bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu
## Ensure this file can only be sourced once
cleanup_loaded=${cleanup_loaded:-}
if [[ -n ${cleanup_loaded} ]]; then
  echo "Warning: This file can only be sourced once"
  return 1
fi
cleanup_loaded=true

function action_clean() {

  header_text "Start Cleanup actions"

  ## Removes unneeded packages
  header_text "Removing unneeded packages"
  "${EXEC}" "${SUDO}" "${APT_GET}" -y --purge autoremove
  sleep "${WAIT_ACTION}"

  ## Removes unused config files
  header_text "Removing unused config files"
  "${EXEC}" "${SUDO}" "${DEBORPHAN}" -n --find-config | "${EXEC}" "${XARGS}" "${SUDO}" "${APT_GET}" -y --purge autoremove
  sleep "${WAIT_ACTION}"

  ## Removes package files that can no longer be downloaded and everything except
  # the lock file in /var/cache/apt/archives, including directories.
  header_text "Cleaned downloaded temporary packages"

  "${EXEC}" "${SUDO}" "${APT_GET}" -y autoclean
  "${EXEC}" "${SUDO}" "${APT_GET}" -y clean

  header_text "Finish Cleanup actions"
  sleep "${WAIT_ACTION}"
}

#
# Standalone
#
if [[ "${FUNCNAME[0]}" != source ]]; then
  base_dir=$(dirname "$0")
  # shellcheck source=base
  source "${base_dir}"/base

  header_text "Cleanup system (standalone version)."

  EXEC=${EXEC:=yes_opp}
  check_root_priv
  action_clean
fi