#!/usr/bin/env bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu
## Ensure this file can only be sourced once
set +u
if [[ "${FUNCNAME[0]}" != source ]]; then
  echo "This file can only be source"
  exit 1
fi
if [[ -n ${maintain_loaded} ]]; then
  echo "Warning: This file can only be sourced once"
  return 1
fi
maintain_loaded=true
set -u

function action_maintain() {
  header_text "Start System update actions"

  ## Updates package lists
  header_text "Updating package lists"
  set -x
  ${EXEC} ${SUDO} ${APT} update
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Updates packages and libraries
  header_text "Updating packages and system libraries"
  set -x
  ${EXEC} ${SUDO} ${APT} full-upgrade -y
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}
  header_text "Finish System update actions"
  sleep ${WAIT_ACTION}
}