#!/usr/bin/env bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu
## Ensure this file can only be sourced once
maintain_loaded=${maintain_loaded:-}
if [[ -n ${maintain_loaded} ]]; then
  echo "Warning: This file can only be sourced once"
  return 1
fi
maintain_loaded=true

function action_maintain() {
  header_text "Start System update actions"

  ## Updates package lists
  header_text "Updating package lists"
  "${EXEC}" "${SUDO}" "${APT}" update
  sleep "${WAIT_ACTION}"

  ## Updates packages and libraries
  header_text "Updating packages and system libraries"
  "${EXEC}" "${SUDO}" "${APT}" full-upgrade -y
  sleep "${WAIT_ACTION}"

  header_text "Finish System update actions"
  sleep "${WAIT_ACTION}"
}

#
# Standalone
#
if [[ "${FUNCNAME[0]}" != source ]]; then
  base_dir=$(dirname "$0")
  # shellcheck source=base
  source "${base_dir}"/base

  header_text "Maintain system (standalone version)."

  EXEC=${EXEC:=yes_opp}
  check_root_priv
  action_maintain
fi