#!/usr/bin/env bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu
## Ensure this file can only be sourced once
if [[ -n ${cleanup_loaded} ]]; then
  echo "Warning: This file can only be sourced once"
  return 1
fi
cleanup_loaded=true
set -u

function action_clean() {
  header_text "Start Cleanup actions"
  ## Removes unneeded packages
  header_text "Removing unneeded packages"
  set -x
  ${EXEC} ${SUDO} ${APT} -y --purge autoremove
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Removes unused config files
  header_text "Removing unused config files"
  set -x
  ${EXEC} ${SUDO} ${DEBORPHAN} -n --find-config | ${EXEC} xargs ${SUDO} ${APT} -y --purge autoremove
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Removes package files that can no longer be downloaded and everything except
  # the lock file in /var/cache/apt/archives, including directories.
  header_text "Cleaned downloaded temporary packages"

  ${EXEC} ${SUDO} ${APT} -y autoclean
  ${EXEC} ${SUDO} ${APT} -y clean
  { set +x; } 2>/dev/null
  header_text "Finish Cleanup actions"
  sleep ${WAIT_ACTION}
}