#!/usr/bin/env bash
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2154,SC2034

# lib_dir will change to point at /usr/lib/ucaresystem during packaging
lib_dir=$(dirname "$0")
share_dir="$(dirname "$0")/../assets"
# shellcheck source=config
source "${lib_dir}/config"

# Flags the already proceed and must be removed from the runner (include short versions also)
own_flags=("--runner=")
# Keep a copy of the arguments,
OLD_ARGS=("$@")
# ... and remove those flags
# https://stackoverflow.com/questions/16860877/remove-an-element-from-a-bash-array
for target in "${own_flags[@]}"; do
  for i in "${!OLD_ARGS[@]}"; do
    if [[ ${OLD_ARGS[i]} =~ $target ]]; then
      unset 'OLD_ARGS[i]'
    fi
  done
done

# parse the command-line
setup_ucaresystem_flags
setup_common_flags
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

common_cmd_options
load_config_file

# Decide if you have to use some special runner
# gui versions needs one
declare -A use_runners
use_runners=([cli]="run_opp" [gui]="${X_SUDO_RUNNER}" [xterm]="${X_SUDO_RUNNER}")

# Map options to executables
declare -A use_dispatch
use_dispatch=([cli]="cli" [gui]="xterm" [xterm]="xterm")

runner=${use_runners[${FLAGS_runner}]}
dispatch=${use_dispatch[${FLAGS_runner}]}
executable="${lib_dir}/ucaresystem-${dispatch}"

"$runner" "$executable" "${OLD_ARGS[@]}"
exit $?
