#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>

set -eu
UCARE_VERSION="4.5.0"
lib_dir="."
base_dir=$(dirname "$0")

source "${base_dir}"/base

terms=(x-terminal-emulator gnome-terminal konsole  i3-sensible-terminal uxterm xterm rxvt)
for t in ${terms[*]}
do
    if [ $(command -v "$t") ]
    then
        detected_term=$t
        break
    fi
done


/usr/bin/pkexec  $(which "${detected_term}") -title 'uCareSystem Core'  -e ucaresystem --wait
