#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>

base_dir=$(dirname "$0")
# shellcheck source=base
source "${base_dir}"/config

function command_help() {
   echo "The pseudo-gui version of the ucaresystem"
}

# shellcheck disable=SC2034
info_text="ucaresystem: pseudo-gui version."
# shellcheck disable=SC2034
command_line_options=("$@")
# shellcheck disable=SC2034
help_action="command_help"
# shellcheck disable=SC2034
manpage="ucaresystem"
basic_setup


#
# Possible runners
#



echo /usr/bin/pkexec  \
  "${X_TERMINAL}" \
  -title 'uCareSystem Core'  \
  "${X_TERMINAL_OPTIONS}" \
  -e "${base_dir}/ucaresystem-cli" \
  "$*" --wait -hold

exit $?