#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


read -rp "Does it run Yes/No? " yn

set -eu
UCARE_VERSION="4.5.0"
base_dir=$(dirname "$0")
# shellcheck source=base
source "${base_dir}"/config
basic_setup

function welcome_screen() {
  clear
  ! cat "$BANNER_FILE"

  if [ "${ASK_CONFIRM}" == "true" ]; then
    ask_yesno "Are you sure ?" resp
    if [[ "${resp}" == "no" ]]; then
      exit 1
    fi
  fi
}



##
## The main process starts here
##


MODE="${DEFAULT_MODE}"
UPGRADE_MODE="next"
SHOW_BANNER=true
EXEC=""
DO_WAIT=false

ARGS=$(getopt -o hvdysmcwu: --long help,version,dryrun,yes,skip,maintain,clean,wait,upgrade: -- "$@")
eval set -- "$ARGS"

while true; do
  case "$1" in
  -d | --dryrun)
    EXEC="echo"
    shift
    ;;
  -y | --yes)
    ASK_CONFIRM=false
    shift
    ;;
  -s | --skip)
    SHOW_BANNER=false
    shift
    ;;
  -w | --wait)
    DO_WAIT=true
    shift
    ;;
  -m | --maintain)
    MODE=maintain
    shift
    ;;
  -c | --clean)
    MODE=clean
    shift
    ;;
  -u | --upgrade)
    MODE=upgrade
    UPGRADE_MODE="$2"
    shift
    shift
    ;;
  *) break ;;
  esac
done

# --help and --version is not our worries
# So must always check root privileges.
check_root_priv


if [ "$SHOW_BANNER" == true ]; then
  welcome_screen
else
  echo "${GREEN}ucaresystem${NORMAL}: All-in-one System Update and maintenance tool."
fi

case "$MODE" in
"maintain")
  source "${base_dir}"/task_check_eol
  source "${base_dir}"/task_maintain
  source "${base_dir}"/task_cleanup
  source "${base_dir}"/task_timeshift
  check_eol
  action_timeshift maintain
  action_maintain
  action_clean
  ;;
"clean")
  source "${base_dir}"/task_check_eol
  source "${base_dir}"/task_cleanup
  source "${base_dir}"/task_timeshift
  check_eol
  action_timeshift clean
  action_clean
  ;;
"upgrade")
  action_upgrade "${UPGRADE_MODE}"
  ;;
esac

check_reboot
header_text "Done"

if [ "$DO_WAIT" == true ]; then
  echo
  read -r -p "Press enter to close the window"
fi
