#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright (C) 2009-2020 Salih Emin <salih@utappia.org>
#
#    Authors: Salih Emin <salih@utappia.org>
#             Ioannis Tsagkatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

if [[ "$(basename "$0")" == *"core"* ]]; then
  echo "Warning: command name is now just 'ucaresystem' ucaresystem-core will be removed in next release."
fi

UCARE_VERSION="4.5.0"
#Config file
if [ -x "/etc/ucaresystem.conf" ]; then
  source /etc/ucaresystem.conf
fi

# Configuration variables and default values
WAIT_ACTION=${WAIT_ACTION:=0}
KEEP_KERNELS=${KEEP_KERNELS:=2}
SHOW_BANNER=${SHOWBANNER:=true}
DEFAULT_MODE=${DEFAULT_MODE:=maintain}
AUTO_REBOOT=${AUTO_REBOOT:=false}
AUTO_REBOOT_TIMEOUT=${AUTO_REBOOT_TIMEOUT:=10}
ASK_CONFIRM=${ASK_CONFIRM:=true}
ENABLE_TIMESHIFT=${ENABLE_TIMESHIFT:=false}
EXEC=""
DO_WAIT=false

## Colors
RED=""
GREEN=""
NORMAL=""
BOLD=""
BOLDOFF=""

set +u
if [[ -z "${NO_COLOR}" ]]; then
  if test -n "$TERM" && test "$TERM" != "dumb"; then
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    NORMAL=$(tput setaf 7)
    BOLD=$(tput bold)
    BOLDOFF=$(tput sgr0)
  fi
fi
set -u

# Programs used
SUDO="/usr/bin/sudo"
DEBORPHAN="/usr/bin/deborphan"
UPDATE_TOOL="/usr/bin/do-release-upgrade"
LSB_RELEASE="/usr/bin/lsb_release"
REBOOT="/sbin/reboot"
LOCALE="/usr/bin/locale"
SED="/bin/sed"
TIMESHIFT="/usr/bin/timeshift"

# use apt or apt-get
if [ -x "/usr/bin/apt" ]; then
  APT="/usr/bin/apt"
else
  APT="/usr/bin/apt-get"
fi

trap trap_handler 1 2 3 6
function trap_handler() {
  { set +x; } 2>/dev/null
  banner "Program interrupt."
  echo "  The program have stop before finished. Your system maybe in an incomplete state."
  echo "  You may need to do:"
  echo "     sudo apt update && sudo apt install -f"
  exit 1
}

function banner() {
  echo -e "${GREEN}${BOLD}***${BOLDOFF} ${1}${NORMAL}"
}

function ask_yesno() {
  prompt=$1
  set -- $(${LOCALE} LC_MESSAGES)
  yesptrn="$1"
  noptrn="$2"
  yesword="$3"
  noword="$4"
  while true; do
    read -rp "${prompt} (${yesword} / ${noword})? " yn
    case $yn in
    ${yesptrn##^})
      response="yes"
      break
      ;;
    ${noptrn##^})
      response="no"
      break
      ;;
    *) echo "${prompt} ${yesword} / ${noword}." ;;
    esac
  done
}

function check_eol() {
  distribution_id=$(${LSB_RELEASE} --id | cut -f2)
  codename=$(${LSB_RELEASE} --codename | cut -f2)

  # distribution_id="Ubuntu" && codename="focal"

  valid_ids=("Debian" "Ubuntu")
  if [[ ! "${valid_ids[*]}" == *"${distribution_id}"* ]]; then
    banner "Your distribution is '${distribution_id}', codename:'${codename}'."
    return
  fi

  case "${distribution_id}" in
  "Debian") DISTRO_INFO="/usr/bin/debian-distro-info" ;;
  "Ubuntu") DISTRO_INFO="/usr/bin/ubuntu-distro-info" ;;
  esac

  supported_distro=$(${DISTRO_INFO} --supported)
  days=$(${DISTRO_INFO} --series="${codename}" --days)

  if [[ "${supported_distro[*]}" == *"${codename}"* ]]; then
    banner "Your distribution '${GREEN}${distribution_id}${NORMAL}', codename:'${GREEN}${codename}${NORMAL}' is not at eol."
    if [ ! "${days}" == "(unknown)" ]; then
      if [[ "${days}" == *"-"* ]]; then
        banner "The was a new distribution version before ${days//-/} days. Consider an upgrade."
      else
        banner "Expect a new version of your distribution in ${days} days."
      fi
    fi
    return
  else
    banner "Your distribution '${distribution_id}', codename:'${codename}' is reach the end of support"
    echo "  The end of support was before ${days//-/} days."
    echo "  Please upgrade your distribution to a latest release!"
    echo "  Try run: $(basename "${0}") --upgrade"
    exit
  fi
}

function check_root_priv() {
  # Checking if the user has run the script with "sudo" or not
  if [[ $EUID -ne 0 ]]; then
    echo -ne "${RED}${BOLD}Error: ${BOLDOFF} '$0'" 1>&2
    echo -ne " ${BOLD}must run with root user privileges.${BOLDOFF}" 1>&2
    echo -ne " ${BOLD}consider running it with 'sudo' ${BOLDOFF}" 1>&2
    printf "\n\n"
    exit 1
  fi
}

function welcome_screen() {
  clear
  echo "_______________________________________________________"
  echo "                                                       "
  echo "            ${GREEN}uCareSystem Core ${UCARE_VERSION}${NORMAL}            "
  echo "            ${GREEN}~~~~~~~~~~~~~~~~~~~~~~~${NORMAL}                      "
  echo "                                                       "
  echo " Welcome to all-in-one System Update and maintenance   "
  echo " assistant app.                                        "
  echo "                                                       "
  echo "                                                       "
  echo " This simple script will automatically         	     "
  echo " refresh your packagelist, download and                "
  echo " install updates (if there are any), remove any old    "
  echo " kernels, obsolete packages and configuration files    "
  echo " to free up disk space, without any need of user       "
  echo " interference                                         "
  echo "                   				                     "
  echo " If you’ve found it useful and saved you time and you  "
  echo " think it is worth of your support, you can make a     "
  echo " donation via PayPal by clicking on the following:     "
  echo "                                                       "
  echo "           ${GREEN}https://www.paypal.me/cerebrux${NORMAL}              "
  echo "_______________________________________________________"
  echo

  if [ "${ASK_CONFIRM}" == "true" ]; then
    ask_yesno "Are you sure ?"
    if [[ "${response}" == "no" ]]; then
      exit 1
    fi
  fi
}

function action_version() {
  echo "$(basename "${0}") version ${UCARE_VERSION}"
  exit
}

function action_maintain() {
  check_root_priv
  banner "Start System update actions"

  ## Updates package lists
  banner "Updating package lists"
  set -x
  ${EXEC} ${SUDO} ${APT} update
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Updates packages and libraries
  banner "Updating packages and system libraries"
  set -x
  ${EXEC} ${SUDO} ${APT} full-upgrade -y
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}
  banner "Finish System update actions"
  sleep ${WAIT_ACTION}
}

function action_clean() {
  check_root_priv
  banner "Start Cleanup actions"
  ## Removes unneeded packages
  banner "Removing unneeded packages"
  set -x
  ${EXEC} ${SUDO} ${APT} -y --purge autoremove
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Removes unused config files
  banner "Removing unused config files"
  set -x
  ${EXEC} ${SUDO} ${DEBORPHAN} -n --find-config | ${EXEC} xargs ${SUDO} ${APT} -y --purge autoremove
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}

  ## Removes package files that can no longer be downloaded and everything except
  # the lock file in /var/cache/apt/archives, including directories.
  banner "Cleaned downloaded temporary packages"
  set -x
  ${EXEC} ${SUDO} ${APT} -y autoclean
  ${EXEC} ${SUDO} ${APT} -y clean
  { set +x; } 2>/dev/null
  banner "Finish Cleanup actions"
  sleep ${WAIT_ACTION}
}

function check_reboot() {
  banner "Checking to see if a reboot is required "
  ## Check to see if a reboot is required
  if [ -f /var/run/reboot-required ]; then
    echo
    echo "${BOLD}${RED}* * * * * * * * * * * * * * * * * *"
    echo "*                                 *"
    echo "* Consider rebooting your system  *"
    echo "* to finish applying updates      *"
    echo "*                                 *"
    echo "* * * * * * * * * * * * * * * * * *${BOLDOFF}${NORMAL}"
    echo
  fi

  if [ "$AUTO_REBOOT" == true ]; then
    banner "Rebooting system"
    echo " ucaresystem will reboot the system in ${AUTO_REBOOT_TIMEOUT} seconds... "
    sleep ${AUTO_REBOOT_TIMEOUT}
    ${REBOOT}
  fi
}

function action_upgrade_EOL() {
  check_root_priv
  curr_date=$(date +%F_%T)

  new_codename=$(/usr/bin/ubuntu-distro-info --supported | tail -1)

  banner "Upgrade to EOL"
  ${EXEC} "/etc/apt/sources.list" "/etc/apt/sources.eol_${curr_date}"
  if [ "$EXEC" == "echo" ]; then
    echo "...skiping updating /etc/apt/sources.list"
  else
    banner "Updating /etc/apt/sources.list"
    cat <<EOT >/etc/apt/sources.list
deb http://old-releases.ubuntu.com/ubuntu/ $new_codename main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ $new_codename-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ $new_codename-security main restricted universe multiverse

EOT
  fi

  ${EXEC} ${SUDO} ${APT} install update-manager-core
  ${EXEC} ${SUDO} ${APT} -y dist-upgrade
  ${EXEC} ${SUDO} ${UPDATE_TOOL}
  banner "Done upgrade to EOL"
}

function action_upgrade() {
  distribution_id=$(${LSB_RELEASE} --id | cut -f2)
  codename=$(${LSB_RELEASE} --codename | cut -f2)

  case "${distribution_id}" in
  "Debian") do_debian_upgade "$1" ;;
  "Ubuntu") do_ubuntu_upgade "$1" ;;
  "LinuxMint")
    echo "Linux Mint is unsupported. Please use the distro tool"
    exit
    ;;
  *)
    echo "Your distribution '${distribution_id}' is unsupported. Please do a pull request."
    exit
    ;;
  esac

}

function do_ubuntu_upgrade() {
  action="$1"
  # Always ask
  ask_yesno "Are you sure ?"
  if [[ "${response}" == "no" ]]; then
    exit 1
  fi

  case "$action" in
  "next")
    action_timeshift
    action_upgrade_next
    ;;
  "development")
    action_timeshift
    action_upgrade_devel
    ;;
  "eol")
    action_timeshift
    action_upgrade_EOL
    ;;
  *)
    echo "Error: unknown upgrade tag '$action'"
    ;;
  esac
}

function do_debian_upgrade() {
  # TODO: Allow to set codename, test if given is newest
  # TODO: Check if it is safe? (try to see if repo exist for PPAs etc.."

  check_root_priv
  curr_date=$(date +%F_%T)

  codename=$(${LSB_RELEASE} --codename | cut -f2)
  new_codename=$(debian-distro-info --supported | tail -1)

  action_timeshift
  action_maintain

  banner "Upgrade to $new_codename from $codename"

  if [ "$EXEC" == "echo" ]; then
    echo "...skiping updating /etc/apt/sources.list"
  else
    banner "Backup /etc/apt/sources.list"
    ${EXEC} cp "/etc/apt/sources.list" "/etc/apt/sources.${codename}_${curr_date}"
    for file in /etc/apt/sources.list.d/*; do
      ${EXEC} cp "$file" "${file}.${codename}_${curr_date}"
    done

    banner "Updating /etc/apt/sources.list"
    ${EXEC} ${SUDO} ${SED} -i "s/${codename}/${new_codename}/g" /etc/apt/sources.list
    ${EXEC} ${SUDO} ${SED} -i "s/${codename}/${new_codename}/g" /etc/apt/sources.list.d/*.list
  fi

  action_maintain
  ${EXEC} ${SUDO} apt dist-upgrade -y

  banner "Done upgrade to $new_codename from $codename"
}

function action_upgrade_next() {
  if [ -x ${UPDATE_TOOL} ]; then
    echo "Error missing ${UPDATE_TOOL}"
    exit 1
  fi

  check_root_priv
  banner "Upgrade to next Release"
  ${EXEC} ${UPDATE_TOOL}
  banner "Done upgrade to next Release"
}

function action_upgrade_devel() {
  if [ -x ${UPDATE_TOOL} ]; then
    echo "Error missing ${UPDATE_TOOL}"
    exit 1
  fi

  check_root_priv
  ${EXEC} ${UPDATE_TOOL} -d
  banner "Done upgrade to next Release"
}

function action_timeshift() {
  if [ "${ENABLE_TIMESHIFT}" == "false" ]; then
    return
  fi

  banner "Make a snapshot with timeshift"
  if [ -z ${TIMESHIFT} ]; then
    echo "timeshift is missing. Skipping ..."
    return
  fi

  distribution_id=$(${LSB_RELEASE} --id | cut -f2)
  curr_date=$(date +%F_%T)
  set -x
  ${EXEC} ${SUDO} ${TIMESHIFT} --create --comments "${distribution_id}-ucaresystem-${curr_date}"
  { set +x; } 2>/dev/null
  sleep ${WAIT_ACTION}
}

function action_help() {
  cat <<EOF
uCareSystem Core $UCARE_VERSION : All-in-one system update and maintenance tool

Usage:
  sudo ucaresystem [options]
  ucaresystem --help|--version

MODES
   -m, --maintenance
      Do normal maintenance jobs. The default action id no option is given.
   -c, --clean
      reclaim some disk space
   -u type, --upgrade=type
          Upgrade ...
OTHER OPTIONS
  -n, --dyrun
    Show only the commands, but do not modify the system
  -y, --yes
    Don't ask for confirmation
  -h, --help
    Display this help text
  -v, --version
    Display program version and exits
  -s, --skip
    Do not show the welcome banner, and do not pause.
  -w, --wait
    Press ENTER to end the program. For the "gui" version

See man page for more info
EOF
  exit
}

##
## The main process starts here
##

MODE="${DEFAULT_MODE}"
UPGRADE_MODE="next"
ARGS=$(getopt -o hvdysmcwu: --long help,version,dryrun,yes,skip,maintain,clean,wait,upgrade: -- "$@")
eval set -- "$ARGS"

while true; do
  case "$1" in
  -h | --help)
    action_help
    shift
    ;;
  -v | --version)
    action_version
    shift
    ;;
  -d | --dryrun)
    EXEC="echo"
    shift
    ;;
  -y | --yes)
    ASK_CONFIRM=false
    shift
    ;;
  -s | --skip)
    SHOW_BANNER=false
    shift
    ;;
  -w | --wait)
    DO_WAIT=true
    shift
    ;;
  -m | --maintain)
    MODE=maintain
    shift
    ;;
  -c | --clean)
    MODE=clean
    shift
    ;;
  -u | --upgrade)
    MODE=upgrade
    UPGRADE_MODE="$2"
    shift
    shift
    ;;
  *) break ;;
  esac
done

if [ "$SHOW_BANNER" == true ]; then
  welcome_screen
fi

case "$MODE" in
"maintain")
  check_eol
  action_timeshift
  action_maintain
  action_clean
  ;;
"clean")
  check_eol
  action_timeshift
  action_clean
  ;;
"upgrade")
  action_upgrade "${UPGRADE_MODE}"
  ;;
esac

check_reboot
banner "Done"

if [ "$DO_WAIT" == true ]; then
  echo
  read -r -p "Press enter to close the window"
fi
