#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>


# This will just call the X/Wayland terminal
# Why a separate program, you may ask
# It's because this will be executed under pkexec and its authorized
# Better authorize this to use the Graphics system that each terminal
# This will help with WSL also.

# shellcheck disable=SC2154,SC2034

# lib_dir will change to point at /usr/lib/ucaresystem during packaging
lib_dir=$(dirname "$0")
# shellcheck source=config
source "${lib_dir}/config"

load_config_file

executable="${lib_dir}/ucaresystem-cli"

"${X_TERMINAL}" "${X_TERMINAL_OPTIONS}" "${executable}" "$@" --wait-gui
exit