#!/bin/bash
#
#    ucaresystem - All-in-one system update and maintenance tool
#    Copyright:
#       2009 Salih Emin <salih@utappia.org>
#       2020 Ioannis Tsagatakis <tsagatakis@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2154,SC2034

if [[ ! "$1" == "--cron" ]]; then
   echo "Warning: command name is now just 'ucaresystem' ucaresystem-core will be removed in next release."
   echo

  function overwrite() { echo -e "\r\033[1A\033[0K$*"; }
  timer=60
  echo
  while [[ $timer != 0 ]]; do
    overwrite "Wait ${timer} secs, or cancel and type the new command ..."
    sleep 1
    timer="$((timer - 1))"
  done
  overwrite " "

  "$(dirname "$0")/ucaresystem" "$@"
  exit
fi

if [[ $EUID -ne 0 ]] ; then
    echo "ucaresystem-core must be run as root or with sudo. Now I will just exit..." 1>&2
    exit 1
fi

set -x
# TODO: Logging framework
{
  sudo apt update
  sudo apt full-upgrade -y
  sudo apt-get -y --purge autoremove
  sudo deborphan -n --find-config | xargs sudo apt-get -y --purge autoremove;
  sudo apt-get -y autoclean; sudo apt-get -y clean
} > ucaresystem.log
